module Refinery
  module Blog
    class Engine < Rails::Engine
      include Refinery::Engine

      isolate_namespace Refinery
      engine_name :refinery_blog

      initializer "register refinerycms_blog plugin", :after => :set_routes_reloader do |app|
        Refinery::Plugin.register do |plugin|
          plugin.pathname = root
          plugin.name = "refinerycms_blog"
          plugin.url = app.routes.url_helpers.refinery_admin_blog_posts_path
          plugin.menu_match = /refinery\/blog\/?(posts|comments|categories)?/
          plugin.activity = {
            :class_name => :'refinery/blog/post',

            # Workaround bug #1193 in refinerycms.
            # Without this line, the route fragment generated by the Refinery's
            # activity dashboard would be refinery_blog_admin_blog_posts_path,
            # which does not exist.
            :url => "refinery_admin_blog_posts_path"
          }
        end
      end

      config.after_initialize do
        Refinery.register_engine(Refinery::Blog)
      end
    end
  end
end
